baseURL = "https://blog.nyanco.top"
languageCode = "zh-cn"
title = "NyanC's Blog"
# theme = "github-style"
theme = "m10c"
# googleAnalytics = "UA-123456-789"
pygmentsCodeFences = true
pygmentsUseClasses = true
enableEmoji = true
# disqusShortname = "nyan-blog"

[params.valine]
    enable = true
    appId = 'ri1SLKJpbyyESG14uQHiwDtc-gzGzoHsz'
    appKey = '2MjdhHpp1yusSckOo8x7YVli'
    notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    verify = false # Verification code
    avatar = 'monsterid'
    placeholder = 'Comment Here...'
    visitor = true
[params]
  author = "NyanC"
  description = "At least I was a Big Dreamer."
  github = "Nayaco"
  email = "me@nyanco.top"
  avatar = "/images/avatar.jpg"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "China"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/Nayaco"
  [[params.social]]
    icon = "rss"
    name = "RSS"
    url = "/index.xml"
    

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3
  [[menu.main]]
    identifier = "friends"
    name = "Friends"
    url = "/friends/"
    weight = 3

